'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const hideNavbarPaths = ['/login', '/signup']

  const shouldHideNavbar = hideNavbarPaths.includes(pathname);
  return (
    <html lang="en">
      <body className={`p-4`}>
        {!shouldHideNavbar && <Header />}
        {children}
      </body>
    </html>
  );
}
